#!/usr/bin/env bash
# Regenerate every brand asset derived from static/logo-icon.svg.
#
# logo-icon.svg is the only hand-maintained artwork; edit it and re-run this.
# Everything below is generated, so don't hand-edit the outputs.
#
#   static/logo-icon-light.svg   the navbar mark
#   static/favicon.ico           16 + 32 + 48
#   static/favicon-32.png
#   static/favicon-48.png
#
# Needs: librsvg (rsvg-convert) and ImageMagick.  brew install librsvg imagemagick
set -euo pipefail

static="$(cd "$(dirname "$0")/.." && pwd)/static"
src="$static/logo-icon.svg"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# ── The navbar mark ─────────────────────────────────────────────────────────
# The navbar is --koetai-blue #1a4a8a, which is also the mark's mid body-
# gradient stop, so the stock artwork sinks into the bar and leaves the fins
# and eye floating on their own. This variant lifts the body to pale blues and
# brightens the teal, which at the 30px the navbar renders it is the difference
# between fins that read and fins that disappear.
#
# CSS custom properties can't do this job: an SVG loaded through <img src> is an
# isolated document that the page's stylesheet never reaches. Hence a file.
{
  echo '<!-- GENERATED by scripts/make_brand_assets.sh from logo-icon.svg. Do not edit. -->'
  sed -e 's|stop-color="#0f3460"|stop-color="#9fc4ea"|' \
      -e 's|stop-color="#1a4a8a"|stop-color="#cfe2f7"|' \
      -e 's|stop-color="#1d5299"|stop-color="#eaf3fc"|' \
      -e 's|#0d8a7c|#3ecfb8|g' \
      "$src"
} > "$static/logo-icon-light.svg"

# ── The favicons ────────────────────────────────────────────────────────────
# A head crop, not the whole fish: at 16px the full mark is an unreadable smear,
# but the bisected four-eyed eye still reads. They keep their alpha channel, so
# the mark sits on the browser's own tab colour instead of a white square.
#
# rsvg-convert, not ImageMagick, does the SVG rendering, for two reasons:
# ImageMagick's own renderer ignores the body gradient and paints the fish
# black, and rasterising each size straight from the vector is sharper than
# downscaling one large render. ImageMagick only assembles the .ico, and needs
# -type TrueColorAlpha there or it palettises the 16x16 frame and drops its
# transparency -- which is the one frame browsers show in the tab bar.
sed 's|viewBox="0 0 100 48"|viewBox="53 -3 46 46"|' "$src" > "$work/head.svg"

for size in 16 32 48; do
  rsvg-convert -w "$size" -h "$size" -o "$work/favicon-$size.png" "$work/head.svg"
done

cp "$work/favicon-32.png" "$static/favicon-32.png"
cp "$work/favicon-48.png" "$static/favicon-48.png"
magick "$work/favicon-16.png" "$work/favicon-32.png" "$work/favicon-48.png" \
       -type TrueColorAlpha "$static/favicon.ico"

echo "wrote logo-icon-light.svg, favicon.ico (16/32/48), favicon-32.png, favicon-48.png"
